function indent(text: string, spaces = 2): string {
  const prefix = " ".repeat(spaces);
  return text
    .split("\n")
    .map((line) => (line ? prefix + line : line))
    .join("\n");
}

export function dtsTemplate(generatedTypes: string): string {
  return `\
// Auto-generated by @shiftapi/vite-plugin. Do not edit.
declare module "@shiftapi/client" {
${indent(generatedTypes)}

  import type createClient from "openapi-fetch";

  export const client: ReturnType<typeof createClient<paths>>;
  export { createClient };
}
`;
}

export function virtualModuleTemplate(
  baseUrl: string,
  devApiPrefix?: string,
): string {
  const baseUrlExpr = devApiPrefix
    ? `import.meta.env.VITE_SHIFTAPI_BASE_URL || (import.meta.env.DEV ? ${JSON.stringify(devApiPrefix)} : ${JSON.stringify(baseUrl)})`
    : `import.meta.env.VITE_SHIFTAPI_BASE_URL || ${JSON.stringify(baseUrl)}`;

  return `\
// Auto-generated by @shiftapi/vite-plugin
import createClient from "openapi-fetch";

/** Pre-configured, fully-typed API client. */
export const client = createClient({
  baseUrl: ${baseUrlExpr},
});

export { createClient };
`;
}
