/**
 * Builds the runtime JavaScript for the virtual "@shiftapi/client" module.
 *
 * This is pure JS — no TypeScript syntax. Type safety comes from the
 * generated .d.ts file that declares the module with full OpenAPI types.
 */
export function buildVirtualModuleSource(baseUrl: string): string {
  return `// Auto-generated by @shiftapi/vite-plugin
import createClient from "openapi-fetch";

/** Pre-configured, fully-typed API client. */
export const client = createClient(${JSON.stringify({ baseUrl })});

export { createClient };
`;
}
