/**
 * Builds the runtime JavaScript for the virtual "@shiftapi/client" module.
 *
 * This is pure JS — no TypeScript syntax. Type safety comes from the
 * generated .d.ts file that declares the module with full OpenAPI types.
 */
export function buildVirtualModuleSource(
  baseUrl: string,
  devApiPrefix?: string
): string {
  const baseUrlExpr = devApiPrefix
    ? `import.meta.env.VITE_SHIFTAPI_BASE_URL || (import.meta.env.DEV ? ${JSON.stringify(devApiPrefix)} : ${JSON.stringify(baseUrl)})`
    : `import.meta.env.VITE_SHIFTAPI_BASE_URL || ${JSON.stringify(baseUrl)}`;

  return `// Auto-generated by @shiftapi/vite-plugin
import createClient from "openapi-fetch";

/** Pre-configured, fully-typed API client. */
export const client = createClient({
  baseUrl: ${baseUrlExpr},
});

export { createClient };
`;
}
