"$schema" = "./node_modules/wrangler/config-schema.json"
name = "shiftapi-web"
main = "./worker/index.ts"
compatibility_date = "2026-03-07"

[assets]
not_found_handling = "single-page-application"
run_worker_first = true
binding = "ASSETS"

[[routes]]
pattern = "shiftapi.dev"
custom_domain = true

[[routes]]
pattern = "www.shiftapi.dev"
custom_domain = true
