function indent(text: string, spaces = 2): string {
  const prefix = " ".repeat(spaces);
  return text
    .split("\n")
    .map((line) => (line ? prefix + line : line))
    .join("\n");
}

/**
 * Inline JS for a bodySerializer that auto-detects File/Blob values
 * and wraps the body in FormData. Falls back to JSON.stringify otherwise.
 */
const BODY_SERIALIZER = `(body) => {
  if (typeof body !== "object" || body === null) return JSON.stringify(body);
  const isBinary = (v) => v instanceof Blob || v instanceof File || v instanceof Uint8Array;
  const values = Object.values(body);
  const hasFile = values.some(
    (v) => isBinary(v) || (Array.isArray(v) && v.some(isBinary)),
  );
  if (!hasFile) return JSON.stringify(body);
  const toBlob = (v) => v instanceof Uint8Array ? new Blob([v]) : v;
  const fd = new FormData();
  for (const [key, value] of Object.entries(body)) {
    if (value === undefined || value === null) continue;
    if (Array.isArray(value)) {
      for (const item of value) fd.append(key, isBinary(item) ? toBlob(item) : String(item));
    } else {
      fd.append(key, isBinary(value) ? toBlob(value) : String(value));
    }
  }
  return fd;
}`;

export function dtsTemplate(generatedTypes: string): string {
  return `\
// Auto-generated by shiftapi. Do not edit.
declare module "@shiftapi/client" {
${indent(generatedTypes)}

  import type createClient from "openapi-fetch";

  export const client: ReturnType<typeof createClient<paths>>;
  export { createClient };
}
`;
}

export function clientJsTemplate(baseUrl: string): string {
  return `\
// Auto-generated by shiftapi. Do not edit.
import createClient from "openapi-fetch";

/** Pre-configured, fully-typed API client. */
export const client = createClient({
  baseUrl: ${JSON.stringify(baseUrl)},
  bodySerializer: ${BODY_SERIALIZER},
});

export { createClient };
`;
}

export function nextClientJsTemplate(
  port: number,
  baseUrl: string,
  devApiPrefix?: string,
): string {
  if (!devApiPrefix) {
    return `\
// Auto-generated by @shiftapi/next. Do not edit.
import createClient from "./openapi-fetch.js";

const baseUrl =
  process.env.NEXT_PUBLIC_SHIFTAPI_BASE_URL || ${JSON.stringify(baseUrl)};

/** Pre-configured, fully-typed API client. */
export const client = createClient({
  baseUrl,
  bodySerializer: ${BODY_SERIALIZER},
});

export { createClient };
`;
  }

  const devServerUrl = `http://localhost:${port}`;
  return `\
// Auto-generated by @shiftapi/next. Do not edit.
import createClient from "./openapi-fetch.js";

const baseUrl =
  process.env.NEXT_PUBLIC_SHIFTAPI_BASE_URL ||
  (typeof window !== "undefined"
    ? ${JSON.stringify(devApiPrefix)}
    : ${JSON.stringify(devServerUrl)});

/** Pre-configured, fully-typed API client. */
export const client = createClient({
  baseUrl,
  bodySerializer: ${BODY_SERIALIZER},
});

export { createClient };
`;
}

export function virtualModuleTemplate(
  baseUrl: string,
  devApiPrefix?: string,
): string {
  const baseUrlExpr = devApiPrefix
    ? `import.meta.env.VITE_SHIFTAPI_BASE_URL || (import.meta.env.DEV ? ${JSON.stringify(devApiPrefix)} : ${JSON.stringify(baseUrl)})`
    : `import.meta.env.VITE_SHIFTAPI_BASE_URL || ${JSON.stringify(baseUrl)}`;

  return `\
// Auto-generated by @shiftapi/vite-plugin
import createClient from "openapi-fetch";

/** Pre-configured, fully-typed API client. */
export const client = createClient({
  baseUrl: ${baseUrlExpr},
  bodySerializer: ${BODY_SERIALIZER},
});

export { createClient };
`;
}
