function indent(text: string, spaces = 2): string {
  const prefix = " ".repeat(spaces);
  return text
    .split("\n")
    .map((line) => (line ? prefix + line : line))
    .join("\n");
}

export function dtsTemplate(generatedTypes: string, openapiImport?: string): string {
  const src = openapiImport ?? "openapi-fetch";
  return `\
// Auto-generated by shiftapi. Do not edit.
declare module "@shiftapi/client" {
${indent(generatedTypes)}

  import type createClient from "${src}";

  export const client: ReturnType<typeof createClient<paths>>;
  export { createClient };
}
`;
}

export function clientJsTemplate(baseUrl: string): string {
  return `\
// Auto-generated by shiftapi. Do not edit.
import createClient from "openapi-fetch";

/** Pre-configured, fully-typed API client. */
export const client = createClient({
  baseUrl: ${JSON.stringify(baseUrl)},
});

export { createClient };
`;
}

export function nextClientJsTemplate(
  port: number,
  baseUrl: string,
  devApiPrefix?: string,
): string {
  if (!devApiPrefix) {
    return `\
// Auto-generated by @shiftapi/next. Do not edit.
import createClient from "./openapi-fetch.js";

const baseUrl =
  process.env.NEXT_PUBLIC_SHIFTAPI_BASE_URL || ${JSON.stringify(baseUrl)};

/** Pre-configured, fully-typed API client. */
export const client = createClient({ baseUrl });

export { createClient };
`;
  }

  const devServerUrl = `http://localhost:${port}`;
  return `\
// Auto-generated by @shiftapi/next. Do not edit.
import createClient from "./openapi-fetch.js";

const baseUrl =
  process.env.NEXT_PUBLIC_SHIFTAPI_BASE_URL ||
  (typeof window !== "undefined"
    ? ${JSON.stringify(devApiPrefix)}
    : ${JSON.stringify(devServerUrl)});

/** Pre-configured, fully-typed API client. */
export const client = createClient({ baseUrl });

export { createClient };
`;
}

export function virtualModuleTemplate(
  baseUrl: string,
  devApiPrefix?: string,
): string {
  const baseUrlExpr = devApiPrefix
    ? `import.meta.env.VITE_SHIFTAPI_BASE_URL || (import.meta.env.DEV ? ${JSON.stringify(devApiPrefix)} : ${JSON.stringify(baseUrl)})`
    : `import.meta.env.VITE_SHIFTAPI_BASE_URL || ${JSON.stringify(baseUrl)}`;

  return `\
// Auto-generated by @shiftapi/vite-plugin
import createClient from "openapi-fetch";

/** Pre-configured, fully-typed API client. */
export const client = createClient({
  baseUrl: ${baseUrlExpr},
});

export { createClient };
`;
}
